spring.data.mongodb.uri=mongodb+srv://budkovgersh_db_user:gIIdkEe2K465LSaN@cluster0.j43ec8j.mongodb.net/?appName=Cluster0

spring.data.mongodb.database=JournalDB
server.port=8082
spring.data.mongodb.auto-index-creation=true